MAX_USERNAME_LENGTH = 150
MAX_EMAIL_LENGTH = 254
MAX_BIO_LENGTH = 1024
CONFIRMATION_CODE_LENGTH = 5

USER_ROLE = "user"
MODERATOR_ROLE = "moderator"
ADMIN_ROLE = "admin"

USERNAME_PATTERN = r'^[\w.@+-]+\Z'
