# Generated by Django 3.2 on 2023-05-17 15:13

from django.db import migrations, models

import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='score',
            field=models.IntegerField(default=5, validators=[reviews.validators.validate_max_min]),
        ),
    ]
