# Generated by Django 3.2 on 2023-05-28 08:56

from django.db import migrations, models

import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[reviews.validators.validate_max_min], verbose_name='Рейтинг произведения'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(default=0, validators=[reviews.validators.validate_max_min]),
        ),
    ]
