# Generated by Django 3.2 on 2023-05-18 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20230517_1549'),
        ('reviews', '0002_review_score'),
    ]

    operations = [
    ]
