# Generated by Django 3.2 on 2023-05-28 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_review_unique_author_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genres', to='reviews.genre')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='reviews.title')),
            ],
            options={
                'verbose_name': 'Жанр произведения',
                'verbose_name_plural': 'Жанры произведения',
            },
        ),
        migrations.AddConstraint(
            model_name='genre_title',
            constraint=models.UniqueConstraint(fields=('title', 'genre'), name='unique_combination_gt'),
        ),
    ]
